spring.datasource.url=jdbc:postgresql://localhost:5432/chirag_db
spring.datasource.username=postgres
spring.datasource.password=Welcome1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
